#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Thu Apr 16 16:35:11 AEST 2026
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=10
shaderPack=ComplementaryReimagined_r5.7.1 + EuphoriaPatches_1.8.6
